//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherInformation.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeatherInformation.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 14.
        /// </summary>
        public static string APIOpenWeatherMapResultsNumber {
            get {
                return ResourceManager.GetString("APIOpenWeatherMapResultsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2.5.
        /// </summary>
        public static string APIVersionOpenWeatherMap {
            get {
                return ResourceManager.GetString("APIVersionOpenWeatherMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City, country.
        /// </summary>
        public static string LocationPageSubTitle {
            get {
                return ResourceManager.GetString("LocationPageSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pick your location.
        /// </summary>
        public static string LocationPageTitle {
            get {
                return ResourceManager.GetString("LocationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CLOUDS.
        /// </summary>
        public static string MainPageCurrentClouds {
            get {
                return ResourceManager.GetString("MainPageCurrentClouds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a %.
        /// </summary>
        public static string MainPageCurrentCloudsUnits {
            get {
                return ResourceManager.GetString("MainPageCurrentCloudsUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FEELS LIKE.
        /// </summary>
        public static string MainPageCurrentFeelsLike {
            get {
                return ResourceManager.GetString("MainPageCurrentFeelsLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a current.
        /// </summary>
        public static string MainPageCurrentHeader {
            get {
                return ResourceManager.GetString("MainPageCurrentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HUMIDITY.
        /// </summary>
        public static string MainPageCurrentHumidity {
            get {
                return ResourceManager.GetString("MainPageCurrentHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a %.
        /// </summary>
        public static string MainPageCurrentHumidityUnits {
            get {
                return ResourceManager.GetString("MainPageCurrentHumidityUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRESSURE.
        /// </summary>
        public static string MainPageCurrentPressure {
            get {
                return ResourceManager.GetString("MainPageCurrentPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hpa.
        /// </summary>
        public static string MainPageCurrentPressureUnits {
            get {
                return ResourceManager.GetString("MainPageCurrentPressureUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RAIN.
        /// </summary>
        public static string MainPageCurrentRain {
            get {
                return ResourceManager.GetString("MainPageCurrentRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mm 3h.
        /// </summary>
        public static string MainPageCurrentRainUnits {
            get {
                return ResourceManager.GetString("MainPageCurrentRainUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SNOW.
        /// </summary>
        public static string MainPageCurrentSnow {
            get {
                return ResourceManager.GetString("MainPageCurrentSnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mm 3h.
        /// </summary>
        public static string MainPageCurrentSnowUnits {
            get {
                return ResourceManager.GetString("MainPageCurrentSnowUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SUN RISE (UTC).
        /// </summary>
        public static string MainPageCurrentSunRise {
            get {
                return ResourceManager.GetString("MainPageCurrentSunRise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SUN SET (UTC).
        /// </summary>
        public static string MainPageCurrentSunSet {
            get {
                return ResourceManager.GetString("MainPageCurrentSunSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WIND.
        /// </summary>
        public static string MainPageCurrentWind {
            get {
                return ResourceManager.GetString("MainPageCurrentWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a m/s.
        /// </summary>
        public static string MainPageCurrentWindUnits {
            get {
                return ResourceManager.GetString("MainPageCurrentWindUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a forecast.
        /// </summary>
        public static string MainPageForecastHeader {
            get {
                return ResourceManager.GetString("MainPageForecastHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City, country.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current Location.
        /// </summary>
        public static string MapPageGetCurrentLocationButton {
            get {
                return ResourceManager.GetString("MapPageGetCurrentLocationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Location.
        /// </summary>
        public static string MapPageSaveLocationButton {
            get {
                return ResourceManager.GetString("MapPageSaveLocationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Location autodetection seems to be disabled in your phone.
        /// </summary>
        public static string NoticeErrorLocationAutodetection {
            get {
                return ResourceManager.GetString("NoticeErrorLocationAutodetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is not stored locations..
        /// </summary>
        public static string NoticeThereIsNotCurrentLocation {
            get {
                return ResourceManager.GetString("NoticeThereIsNotCurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a en.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DAY.
        /// </summary>
        public static string SelectedDatePageDay {
            get {
                return ResourceManager.GetString("SelectedDatePageDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EVENING.
        /// </summary>
        public static string SelectedDatePageEvening {
            get {
                return ResourceManager.GetString("SelectedDatePageEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MORNING.
        /// </summary>
        public static string SelectedDatePageMorning {
            get {
                return ResourceManager.GetString("SelectedDatePageMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NIGHT.
        /// </summary>
        public static string SelectedDatePageNight {
            get {
                return ResourceManager.GetString("SelectedDatePageNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forecast day numbers.
        /// </summary>
        public static string SettingsForecastDayNumbersHeader {
            get {
                return ResourceManager.GetString("SettingsForecastDayNumbersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 5-Day Forecast.
        /// </summary>
        public static string SettingsForecastDayNumbersSelectionFive {
            get {
                return ResourceManager.GetString("SettingsForecastDayNumbersSelectionFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 14-Day Forecast.
        /// </summary>
        public static string SettingsForecastDayNumbersSelectionFourteen {
            get {
                return ResourceManager.GetString("SettingsForecastDayNumbersSelectionFourteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 10-Day Forecast.
        /// </summary>
        public static string SettingsForecastDayNumbersSelectionTen {
            get {
                return ResourceManager.GetString("SettingsForecastDayNumbersSelectionTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string SettingsLanguageHeader {
            get {
                return ResourceManager.GetString("SettingsLanguageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a english.
        /// </summary>
        public static string SettingsLanguageSelectionEnglish {
            get {
                return ResourceManager.GetString("SettingsLanguageSelectionEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spanish.
        /// </summary>
        public static string SettingsLanguageSelectionSpanish {
            get {
                return ResourceManager.GetString("SettingsLanguageSelectionSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a settings.
        /// </summary>
        public static string SettingsPageHeaderSettings {
            get {
                return ResourceManager.GetString("SettingsPageHeaderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Temperature units.
        /// </summary>
        public static string SettingsTemperatureUnitsHeader {
            get {
                return ResourceManager.GetString("SettingsTemperatureUnitsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a celsius.
        /// </summary>
        public static string SettingsTemperatureUnitsSelectionCentigrade {
            get {
                return ResourceManager.GetString("SettingsTemperatureUnitsSelectionCentigrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fahrenheit.
        /// </summary>
        public static string SettingsTemperatureUnitsSelectionFahrenheit {
            get {
                return ResourceManager.GetString("SettingsTemperatureUnitsSelectionFahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ºC.
        /// </summary>
        public static string TemperatureUnitsCentigradeSymbol {
            get {
                return ResourceManager.GetString("TemperatureUnitsCentigradeSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ºF.
        /// </summary>
        public static string TemperatureUnitsFahrenheitSymbol {
            get {
                return ResourceManager.GetString("TemperatureUnitsFahrenheitSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The location master switch might be off or location service is unavailable..
        /// </summary>
        public static string UnavailableAutomaticCurrentLocationMessageBox {
            get {
                return ResourceManager.GetString("UnavailableAutomaticCurrentLocationMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.openweathermap.org/data/{0}/weather?lat={1}&amp;lon={2}&amp;cnt=1.
        /// </summary>
        public static string URIAPIOpenWeatherMapCurrent {
            get {
                return ResourceManager.GetString("URIAPIOpenWeatherMapCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.openweathermap.org/data/{0}/forecast/daily?lat={1}&amp;lon={2}&amp;cnt={3}&amp;mode=json.
        /// </summary>
        public static string URIAPIOpenWeatherMapForecast {
            get {
                return ResourceManager.GetString("URIAPIOpenWeatherMapForecast", resourceCulture);
            }
        }
    }
}
